import { ExplorerEntityType } from './explorer.types';

export interface EntityRegistryEntry {
  collection: string;
  titleFields: string[];
  subtitleFields?: string[];
  statusField?: string;
  ownerFields?: string[];
  auditEntityType?: string;
  chainTemplate: Array<{ key: string; label: string; fk?: string; entityType?: ExplorerEntityType }>;
  fkMap?: Record<string, ExplorerEntityType>;
}

export const ENTITY_REGISTRY: Record<ExplorerEntityType, EntityRegistryEntry> = {
  project: {
    collection: 'proj_projects',
    titleFields: ['name'],
    subtitleFields: ['code', 'client'],
    statusField: 'status',
    ownerFields: ['projectManager'],
    auditEntityType: 'project',
    chainTemplate: [
      { key: 'planning', label: 'Planning', entityType: 'project' },
      { key: 'boq', label: 'BOQ', entityType: 'boq' },
      { key: 'mr', label: 'Material Requirement', entityType: 'material-requirement' },
      { key: 'procurement', label: 'Procurement', entityType: 'purchase-request' },
      { key: 'execution', label: 'Site Execution', entityType: 'site' },
      { key: 'finance', label: 'Budget & Finance', entityType: 'vendor-bill' },
      { key: 'completion', label: 'Completion', entityType: 'milestone' },
    ],
    fkMap: {},
  },
  site: {
    collection: 'proj_sites',
    titleFields: ['name', 'code'],
    subtitleFields: ['city', 'location'],
    statusField: 'status',
    ownerFields: ['siteEngineer'],
    chainTemplate: [
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
      { key: 'site', label: 'Site' },
      { key: 'mr', label: 'Material Requirements', entityType: 'material-requirement' },
      { key: 'consumption', label: 'Consumption', entityType: 'consumption' },
    ],
    fkMap: { projectId: 'project' },
  },
  boq: {
    collection: 'proj_boq_lines',
    titleFields: ['description', 'itemCode'],
    subtitleFields: ['itemCode'],
    chainTemplate: [
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
      { key: 'boq', label: 'BOQ Line' },
      { key: 'mr', label: 'Material Requirement', entityType: 'material-requirement' },
      { key: 'pr', label: 'Purchase Request', entityType: 'purchase-request' },
    ],
    fkMap: { projectId: 'project' },
  },
  'material-requirement': {
    collection: 'proj_material_requirements',
    titleFields: ['title', 'mrNumber'],
    statusField: 'status',
    ownerFields: ['requestedBy'],
    chainTemplate: [
      { key: 'boq', label: 'BOQ', entityType: 'boq' },
      { key: 'mr', label: 'Material Requirement' },
      { key: 'pr', label: 'Purchase Request', fk: 'purchaseRequisitionId', entityType: 'purchase-request' },
      { key: 'po', label: 'Purchase Order', entityType: 'purchase-order' },
    ],
    fkMap: { projectId: 'project', purchaseRequisitionId: 'purchase-request' },
  },
  'purchase-request': {
    collection: 'proc_purchase_requests',
    titleFields: ['prNumber'],
    subtitleFields: ['title'],
    statusField: 'status',
    ownerFields: ['requestedBy'],
    auditEntityType: 'purchase_request',
    chainTemplate: [],
    fkMap: { projectId: 'project' },
  },
  rfq: {
    collection: 'proc_rfqs',
    titleFields: ['rfqNumber', 'title'],
    statusField: 'status',
    chainTemplate: [
      { key: 'pr', label: 'Purchase Request', fk: 'purchaseRequisitionId', entityType: 'purchase-request' },
      { key: 'rfq', label: 'RFQ' },
      { key: 'quotation', label: 'Quotations', entityType: 'quotation' },
      { key: 'po', label: 'Purchase Order', entityType: 'purchase-order' },
    ],
    fkMap: { purchaseRequisitionId: 'purchase-request', projectId: 'project' },
  },
  quotation: {
    collection: 'proc_quotations',
    titleFields: ['quotationNumber'],
    statusField: 'status',
    chainTemplate: [
      { key: 'rfq', label: 'RFQ', fk: 'rfqId', entityType: 'rfq' },
      { key: 'quotation', label: 'Quotation' },
      { key: 'vendor', label: 'Vendor', fk: 'vendorId', entityType: 'vendor' },
      { key: 'po', label: 'Awarded PO', entityType: 'purchase-order' },
    ],
    fkMap: { rfqId: 'rfq', vendorId: 'vendor' },
  },
  'purchase-order': {
    collection: 'proc_purchase_orders',
    titleFields: ['poNumber'],
    statusField: 'status',
    chainTemplate: [
      { key: 'pr', label: 'PR', fk: 'purchaseRequisitionId', entityType: 'purchase-request' },
      { key: 'po', label: 'Purchase Order' },
      { key: 'grn', label: 'GRN', entityType: 'grn' },
      { key: 'bill', label: 'Vendor Bill', entityType: 'vendor-bill' },
    ],
    fkMap: { purchaseRequisitionId: 'purchase-request', vendorId: 'vendor', projectId: 'project' },
  },
  grn: {
    collection: 'inv_grns',
    titleFields: ['grnNumber'],
    statusField: 'status',
    auditEntityType: 'grn',
    chainTemplate: [
      { key: 'po', label: 'Purchase Order', fk: 'purchaseOrderId', entityType: 'purchase-order' },
      { key: 'grn', label: 'GRN' },
      { key: 'warehouse', label: 'Warehouse', fk: 'warehouseId', entityType: 'warehouse-material' },
      { key: 'issue', label: 'Material Issue', entityType: 'material-issue' },
      { key: 'consumption', label: 'Consumption', entityType: 'consumption' },
    ],
    fkMap: { purchaseOrderId: 'purchase-order', warehouseId: 'warehouse-material', projectId: 'project', vendorId: 'vendor' },
  },
  'warehouse-material': {
    collection: 'inv_materials',
    titleFields: ['name', 'code'],
    statusField: 'status',
    chainTemplate: [
      { key: 'grn', label: 'GRN', entityType: 'grn' },
      { key: 'stock', label: 'Warehouse Stock' },
      { key: 'issue', label: 'Material Issue', entityType: 'material-issue' },
      { key: 'consumption', label: 'Site Consumption', entityType: 'consumption' },
    ],
    fkMap: {},
  },
  'material-issue': {
    collection: 'inv_material_issues',
    titleFields: ['issueNumber'],
    statusField: 'status',
    ownerFields: ['issuedTo'],
    chainTemplate: [
      { key: 'warehouse', label: 'Warehouse', fk: 'warehouseId', entityType: 'warehouse-material' },
      { key: 'issue', label: 'Material Issue' },
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
      { key: 'consumption', label: 'Consumption', entityType: 'consumption' },
    ],
    fkMap: { warehouseId: 'warehouse-material', projectId: 'project', siteId: 'site' },
  },
  consumption: {
    collection: 'cons_entries',
    titleFields: ['entryType', 'materialId'],
    statusField: 'entryType',
    chainTemplate: [
      { key: 'issue', label: 'Material Issue', fk: 'materialIssueId', entityType: 'material-issue' },
      { key: 'consumption', label: 'Consumption' },
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
      { key: 'milestone', label: 'Milestone', entityType: 'milestone' },
    ],
    fkMap: { projectId: 'project', siteId: 'site', materialIssueId: 'material-issue' },
  },
  vendor: {
    collection: 'proc_vendors',
    titleFields: ['name'],
    subtitleFields: ['code'],
    statusField: 'status',
    ownerFields: ['contactPerson'],
    auditEntityType: 'vendor',
    chainTemplate: [
      { key: 'vendor', label: 'Vendor' },
      { key: 'pr', label: 'Open PRs', entityType: 'purchase-request' },
      { key: 'po', label: 'Purchase Orders', entityType: 'purchase-order' },
      { key: 'bill', label: 'Vendor Bills', entityType: 'vendor-bill' },
      { key: 'payment', label: 'Payments', entityType: 'payment' },
    ],
    fkMap: {},
  },
  'vendor-bill': {
    collection: 'fin_vendor_bills',
    titleFields: ['billNumber', 'invoiceNumber'],
    subtitleFields: ['invoiceNumber'],
    statusField: 'status',
    auditEntityType: 'vendor_bill',
    chainTemplate: [
      { key: 'bill', label: 'Vendor Bill' },
      { key: 'po', label: 'Purchase Order', fk: 'purchaseOrderId', entityType: 'purchase-order' },
      { key: 'grn', label: 'GRN', fk: 'grnId', entityType: 'grn' },
      { key: 'warehouse', label: 'Warehouse', entityType: 'warehouse-material' },
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
      { key: 'budget', label: 'Budget Impact' },
      { key: 'payment', label: 'Payment', entityType: 'payment' },
      { key: 'cashflow', label: 'Cash Flow' },
    ],
    fkMap: { vendorId: 'vendor', projectId: 'project', purchaseOrderId: 'purchase-order', grnId: 'grn' },
  },
  payment: {
    collection: 'fin_payments',
    titleFields: ['paymentNumber'],
    statusField: 'status',
    auditEntityType: 'payment',
    chainTemplate: [
      { key: 'bill', label: 'Vendor Bill', fk: 'vendorBillId', entityType: 'vendor-bill' },
      { key: 'payment', label: 'Payment' },
      { key: 'cashflow', label: 'Cash Flow' },
      { key: 'executive', label: 'Executive Brief' },
    ],
    fkMap: { vendorBillId: 'vendor-bill', vendorId: 'vendor', projectId: 'project' },
  },
  equipment: {
    collection: 'equip_equipment',
    titleFields: ['name', 'code'],
    statusField: 'status',
    ownerFields: ['assignedOperatorName'],
    chainTemplate: [
      { key: 'equip', label: 'Equipment' },
      { key: 'project', label: 'Project', fk: 'currentProjectId', entityType: 'project' },
      { key: 'fuel', label: 'Fuel', entityType: 'fuel-entry' },
      { key: 'maint', label: 'Maintenance', entityType: 'maintenance' },
      { key: 'consumption', label: 'Consumption', entityType: 'consumption' },
    ],
    fkMap: { currentProjectId: 'project' },
  },
  'fleet-vehicle': {
    collection: 'fleet_vehicles',
    titleFields: ['registrationNumber', 'name'],
    statusField: 'status',
    chainTemplate: [
      { key: 'vehicle', label: 'Fleet Vehicle' },
      { key: 'project', label: 'Project', fk: 'currentProjectId', entityType: 'project' },
      { key: 'fuel', label: 'Fuel', entityType: 'fuel-entry' },
      { key: 'maintenance', label: 'Maintenance', entityType: 'maintenance' },
    ],
    fkMap: { currentProjectId: 'project' },
  },
  maintenance: {
    collection: 'maint_work_orders',
    titleFields: ['woNumber', 'title'],
    statusField: 'status',
    chainTemplate: [
      { key: 'equip', label: 'Equipment', fk: 'equipmentId', entityType: 'equipment' },
      { key: 'wo', label: 'Work Order' },
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
    ],
    fkMap: { equipmentId: 'equipment', projectId: 'project' },
  },
  'fuel-entry': {
    collection: 'equip_fuel_entries',
    titleFields: ['entryNumber'],
    chainTemplate: [
      { key: 'equip', label: 'Equipment', fk: 'equipmentId', entityType: 'equipment' },
      { key: 'fuel', label: 'Fuel Entry' },
      { key: 'cost', label: 'Cost Impact' },
      { key: 'project', label: 'Project', entityType: 'project' },
    ],
    fkMap: { equipmentId: 'equipment' },
  },
  operator: {
    collection: 'equip_operators',
    titleFields: ['name'],
    chainTemplate: [
      { key: 'employee', label: 'Employee', fk: 'employeeId', entityType: 'employee' },
      { key: 'equip', label: 'Equipment', fk: 'equipmentId', entityType: 'equipment' },
      { key: 'project', label: 'Project', entityType: 'project' },
    ],
    fkMap: { employeeId: 'employee', equipmentId: 'equipment' },
  },
  employee: {
    collection: 'wf_employees',
    titleFields: ['name', 'employeeId'],
    subtitleFields: ['designation', 'department'],
    statusField: 'currentStatus',
    chainTemplate: [
      { key: 'employee', label: 'Employee' },
      { key: 'attendance', label: 'Attendance', entityType: 'attendance' },
      { key: 'training', label: 'Training & Certification' },
      { key: 'permit', label: 'Permit', entityType: 'permit' },
      { key: 'safety', label: 'Safety', entityType: 'safety-incident' },
      { key: 'productivity', label: 'Productivity' },
      { key: 'project', label: 'Project', fk: 'assignedProjectId', entityType: 'project' },
    ],
    fkMap: { assignedProjectId: 'project', assignedSiteId: 'site' },
  },
  team: {
    collection: 'wf_teams',
    titleFields: ['name', 'code'],
    statusField: 'status',
    chainTemplate: [
      { key: 'team', label: 'Team' },
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
      { key: 'attendance', label: 'Attendance', entityType: 'attendance' },
      { key: 'productivity', label: 'Productivity' },
    ],
    fkMap: { projectId: 'project', siteId: 'site' },
  },
  attendance: {
    collection: 'wf_attendance',
    titleFields: ['date'],
    statusField: 'status',
    chainTemplate: [
      { key: 'employee', label: 'Employee', fk: 'employeeId', entityType: 'employee' },
      { key: 'attendance', label: 'Attendance' },
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
    ],
    fkMap: { employeeId: 'employee', projectId: 'project' },
  },
  permit: {
    collection: 'wf_permits',
    titleFields: ['permitNumber', 'workType'],
    statusField: 'status',
    auditEntityType: 'work_permit',
    chainTemplate: [
      { key: 'employee', label: 'Requester', entityType: 'employee' },
      { key: 'permit', label: 'Permit' },
      { key: 'safety', label: 'Safety Review', entityType: 'safety-incident' },
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
      { key: 'milestone', label: 'Blocked Milestone', entityType: 'milestone' },
    ],
    fkMap: { projectId: 'project', siteId: 'site' },
  },
  'safety-incident': {
    collection: 'wf_safety_incidents',
    titleFields: ['incidentNumber', 'title'],
    statusField: 'status',
    chainTemplate: [
      { key: 'incident', label: 'Safety Incident' },
      { key: 'permit', label: 'Related Permit', entityType: 'permit' },
      { key: 'capa', label: 'CAPA', entityType: 'capa' },
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
    ],
    fkMap: { projectId: 'project' },
  },
  inspection: {
    collection: 'wf_quality_inspections',
    titleFields: ['inspectionNumber', 'inspectionType'],
    statusField: 'status',
    auditEntityType: 'quality_inspection',
    chainTemplate: [
      { key: 'inspection', label: 'Inspection' },
      { key: 'ncr', label: 'NCR', entityType: 'ncr' },
      { key: 'capa', label: 'CAPA', entityType: 'capa' },
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
    ],
    fkMap: { projectId: 'project' },
  },
  ncr: {
    collection: 'wf_ncr',
    titleFields: ['ncrNumber', 'title'],
    statusField: 'status',
    auditEntityType: 'ncr',
    chainTemplate: [
      { key: 'inspection', label: 'Inspection', entityType: 'inspection' },
      { key: 'ncr', label: 'NCR' },
      { key: 'capa', label: 'CAPA', entityType: 'capa' },
      { key: 'milestone', label: 'Milestone Impact', entityType: 'milestone' },
    ],
    fkMap: { projectId: 'project', inspectionId: 'inspection' },
  },
  capa: {
    collection: 'wf_capa',
    titleFields: ['capaNumber', 'title'],
    statusField: 'status',
    auditEntityType: 'capa',
    chainTemplate: [
      { key: 'ncr', label: 'NCR', fk: 'ncrId', entityType: 'ncr' },
      { key: 'capa', label: 'CAPA' },
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
    ],
    fkMap: { ncrId: 'ncr', projectId: 'project' },
  },
  document: {
    collection: 'platform_documents',
    titleFields: ['title'],
    subtitleFields: ['category'],
    statusField: 'approvalStatus',
    chainTemplate: [
      { key: 'document', label: 'Document' },
      { key: 'entity', label: 'Linked Entity' },
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
      { key: 'compliance', label: 'Compliance', entityType: 'compliance-record' },
    ],
    fkMap: { projectId: 'project' },
  },
  'compliance-record': {
    collection: 'comp_records',
    titleFields: ['documentNumber', 'documentType'],
    statusField: 'status',
    auditEntityType: 'compliance_record',
    chainTemplate: [
      { key: 'compliance', label: 'Compliance Record' },
      { key: 'entity', label: 'Linked Asset/Employee' },
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
      { key: 'permit', label: 'Permit Gate', entityType: 'permit' },
    ],
    fkMap: { projectId: 'project', entityId: 'equipment' },
  },
  milestone: {
    collection: 'proj_milestones',
    titleFields: ['name'],
    statusField: 'status',
    chainTemplate: [
      { key: 'project', label: 'Project', fk: 'projectId', entityType: 'project' },
      { key: 'depends', label: 'Dependencies', entityType: 'purchase-request' },
      { key: 'milestone', label: 'Milestone' },
      { key: 'completion', label: 'Project Completion', entityType: 'project' },
    ],
    fkMap: { projectId: 'project' },
  },
};
